import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettierConfig from 'eslint-config-prettier';
import tailwindCanonicalClasses from 'eslint-plugin-tailwind-canonical-classes';

const eslintConfig = defineConfig([
	...nextVitals,
	...nextTs,
	prettierConfig,
	{
		plugins: {
			'tailwind-canonical-classes': tailwindCanonicalClasses,
		},
		rules: {
			'tailwind-canonical-classes/tailwind-canonical-classes': [
				'warn',
				{
					cssPath: './src/app/globals.css',
				},
			],
		},
	},
	// Override default ignores of eslint-config-next.
	globalIgnores([
		// Default ignores of eslint-config-next:
		'.next/**',
		'out/**',
		'build/**',
		'next-env.d.ts',
		// Generated WASM glue code (auto-generated by wasm-pack)
		'public/wasm/**',
		// Service workers
		'public/workers/**',
	]),
]);

export default eslintConfig;
